### ISSUE TITLE
PEP 8 encourages implicit booleans.

### ISSUE THREAD

**Issue by coady** [amontalenti/elements-of-python-style#1]
There are a few examples of `if len(obj) > 0` instead of `if obj`.

**Comment by amontalenti** [comment]
Is your view that `len(obj) > 0` should never be used?

**Comment by ramalho** [comment]
The semantics of `bool()` are explicit: it uses `__len__` when `__bool__` is absent, so that is a big argument to prefer `if my_collection:` over `if len(my_collection):`.

**Comment by ramalho** [comment]
Actually, there's no need to invoke the Data Model to justify this when the tutorial is so clear: "anything with a non-zero length is true, empty sequences are false", from [Python tutorial, section 3.2. First Steps Towards Programming](https://docs.python.org/3/tutorial/introduction.html#first-steps-towards-programming).

**Comment by amontalenti** [comment]
@ramalho I see, this does seem like something I should revise then.

**Comment by coady** [comment]
And it's literally an example used in PEP 8:

```
For sequences, (strings, lists, tuples), use the fact that empty sequences are false.

Yes: if not seq:
     if seq:

No: if len(seq)
    if not len(seq)
```
