### ISSUE TITLE
import conventions

### ISSUE THREAD

**Issue by IuryAlves** [amontalenti/elements-of-python-style#14]
I like to organize my imports in this way:
- 1º import builtins
- 2º from builtins import something
- 3º import third-party-modules
- 4º from third-party-modules import something
- 5º import my_module
- 6º from my_module import something_that_is_mine

Example:

```
# builtin
import urllib
from os import getenv

# third-party
import pygame
from fsm import Fsm

# mine
import colors
from chars import BaseChar

```

**Comment by amontalenti** [comment]
These are the import rules from PEP8:

> Imports should be grouped in the following order:
> - standard library imports
> - related third party imports
> - local application/library specific imports
> 
> You should put a blank line between each group of imports.
> 
> Put any relevant **all** specification after the imports.

Your improvement here is to suggest you should put `from x import y` statements after plain `import x` statements?

**Comment by IuryAlves** [comment]
No. Sorry i didn't realize that pep8 already has import rules. Please ignore this issue.

**Comment by amontalenti** [comment]
@IuryAlves No problem. Thanks for stopping by in any case :grin: -- hope the guide was helpful.

Closing the issue.

**Comment by IuryAlves** [comment]
It's quite awesome =D
