### ISSUE TITLE
Reconsider the suggestion of one-char "_" label, due to gettext.install()

### ISSUE THREAD

**Issue by RealJTG** [amontalenti/elements-of-python-style#20]
> With tuple unpacking, using _ as a throwaway label is also OK. 

Just make sure you don't use something like gettext :)

``` python
import gettext
gettext.install(...)

print _('This is a translatable string and _ function in __builtins__')
```

**Comment by amontalenti** [comment]
Quite a few people raised this, but I am not quite sure what to do. `gettext.install()` seems at fault here -- it seems quite strange to steal the "_" label from everyone for this use case.

**Comment by ulope** [comment]
`gettext.install()` indeed looks like an ugly hack. However using `_` as the import name for gettext like L10N tools is quite common even without it. For example django's documentation uses it throughout.

**Comment by amontalenti** [comment]
@ulope Yes, I agree that it's common. I guess for the people who use it, they'll just have to pick a different one-char throwaway label (like `__`), which is fine. Closing this since I don't think it warrants changes to the guide.
