### ISSUE TITLE
Chinese version available

### ISSUE THREAD

**Issue by williamfzc** [amontalenti/elements-of-python-style#38]
Learn a lot from your post! thanks for writing this, it really solves some problems in our team :) 👍 
I think it will help someone else who using Chinese only, so I translated it into Chinese.

The link: 
https://github.com/williamfzc/elements-of-python-style

**Comment by amontalenti** [comment]
@williamfzc This is amazing! Thanks for putting this together.

I wonder what would be the best way to handle translations like this. Should I include your translation in the core project (I am glad to do so)... do you know of any Github other projects that do this well?

**Comment by blaisep** [comment]
@amontalenti  Yes, the Docker Cheat Sheet project has a folder for the Chinese edition:  https://github.com/wsargent/docker-cheat-sheet/tree/master/zh-cn

**Comment by williamfzc** [comment]
@amontalenti Feel free to do it. It's my pleasure:) 
@blaisep 's idea may helps.

**Comment by amontalenti** [comment]
Closed by PR #39.
