### ISSUE TITLE
Use of numpy style or google style docstrings

### ISSUE THREAD

**Issue by glenfant** [amontalenti/elements-of-python-style#8]
Google style or numpy style docstrings are easier to read in the source code than the "old" Sphinx style. In addition, these "new" docstring styles are supported OTB by the latest Sphinx.

http://sphinx-doc.org/ext/napoleon.html
http://sphinx-doc.org/ext/example_google.html

**Comment by amontalenti** [comment]
@glenfant Thanks for the suggestion. This was also suggested in PR #4, where this is some discussion of it. I plan on evaluating Google style in the next couple days and once I do, I'll likely update the recommendation.

**Comment by amontalenti** [comment]
Closing in favor of PR #4.
